################################################################################
# MODULAIR APPLICATION MANIFEST
################################################################################
# Below is a list of application packages which will be available to the 
# modulair framework.
# 
# These application packages should be located in the directory you set in the
# 'application_path' param in the file modulair_core.launch
#
# Please use '#' to comment out unwanted applications
################################################################################

modulair_app_screen_saver
modulair_app_tron
modulair_app_pic_flyer
# modulair_app_wallball
